### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [dongcodebmt/VX5-591G-Hackintosh#1]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ??  Right now it's fn + f12 and fn + key pause.  My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by dongcodebmt** [comment]
You need to determine the EC of brightness up and down keys, see instructions [here](https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/)
After obtaining the EC of brightness up and down keys, you need to patch rename _QXX to XQXX
Get SSDT [https://github.com/jsassu20/OpenCore-HotPatching-Guide/blob/master/17-Brightness%20Shortcut%20Patch/SSDT-BKeyQ11Q12-LenovoAir.dsl](https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/) then replace XQ11 and XQ12 with your EC and compile it

Maybe EC up and down your brightness keys like me, so you can try my patch. If lucky it will work
https://github.com/dongcodebmt/VX5-591G-OpenCore#guide

**Comment by dongcodebmt** [comment]
You need to determine the EC of brightness up and down keys, see instructions [here](https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/)
After obtaining the EC of brightness up and down keys, you need to patch rename _QXX to XQXX
Get SSDT [here](https://github.com/jsassu20/OpenCore-HotPatching-Guide/blob/master/17-Brightness%20Shortcut%20Patch/SSDT-BKeyQ11Q12-LenovoAir.dsl) then replace XQ11 and XQ12 with your EC and compile it

Maybe EC up and down your brightness keys like me, so you can try my patch. If lucky it will work
https://github.com/dongcodebmt/VX5-591G-OpenCore#guide

**Comment by dongcodebmt** [comment]
You need to determine the EC of the brightness up and down keys, see instructions [here](https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/)
After obtaining the EC of the brightness up and down keys, you need to patch rename _QXX to XQXX
Get SSDT [here](https://github.com/jsassu20/OpenCore-HotPatching-Guide/blob/master/17-Brightness%20Shortcut%20Patch/SSDT-BKeyQ11Q12-LenovoAir.dsl) then replace XQ11 and XQ12 with your EC and compile it

Maybe the EC of the keys up and down your brightness like me, so you can try my patch. If lucky it will work
https://github.com/dongcodebmt/VX5-591G-OpenCore#guide

**Comment by marcinkk** [comment]
I attached kext acpidebug to the config file but when I press fn + arrow right / left, the console does not show information about pressing this shortcut.

**Comment by dongcodebmt** [comment]
It does not show because you have not yet applied "Add DSDT Debug Methods". Try _Q11 and _Q12 like mine to see if it works.

**Comment by marcinkk** [comment]
I understand, but where do I add this patch, I use opencore and only add ssdt files to the config file.  In the opencore tutorial, I didn't see them add a dsdt file.  Do i think wrong ??

**Comment by dongcodebmt** [comment]
I also don't know how to find it on OpenCore.

**Comment by dongcodebmt** [comment]
I found a tutorial [here](https://github.com/jsassu20/OpenCore-HotPatching-Guide/tree/master/20-ACPIDebug). Hope it helps

**Comment by marcinkk** [comment]
Thank you for this tutorial.  Adds the acpidebug.kext file and the ssdt and patch files from the ssdt file to config.plist.  Restarts the system and press the shortcut fn + arrow right / left but in console nothing appears that I pressed these keys on the keyboard.  I don't know what is wrong anymore and I can't adapt this tutorial to my needs.
