### ISSUE TITLE
Audio HDMI not work

### ISSUE THREAD

**Issue by lehmartins17** [dongcodebmt/VX5-591G-Hackintosh#1]
Please, help for audio HDMI, not work :(

**Comment by dongcodebmt** [comment]
I am stuck at this problem. I will try to fix it.

**Comment by lehmartins17** [comment]
> I am stuck at this problem. I will try to fix it.

Okay, I'm looking forward to having it working! I already managed it once, but when restarting it stopped working again. I've been in this fight for months. If you can tell me please ?!

**Comment by dongcodebmt** [comment]
I think it will not work. Tried many ways but still didn't work :(

**Comment by lehmartins17** [comment]
> I think it will not work. Tried many ways but still didn't work :(

But why is that? I really need HDMI audio, it worked once. But when restarting MacOS again, it stopped! : '(
Thanks for your effort. Contributed too much 👍

**Comment by dongcodebmt** [comment]
> > I think it will not work. Tried many ways but still didn't work :(
> 
> But why is that? I really need HDMI audio, it worked once. But when restarting MacOS again, it stopped! : '(
> Thanks for your effort. Contributed too much 👍

As I know, the 8086:a171 device is not supported. It needs to patch framebuffer and add kext FakePCIID. But when I added the sound stopped working. It could be because the kext is outdated or for some reason.

**Comment by dongcodebmt** [comment]
Please check out FakePCIID.kext. I have edited it. Now HDMI audio is working

**Comment by lehmartins17** [comment]
> Please check out FakePCIID.kext. I have edited it. Now HDMI audio is working

You are extraordinary! The hdmi audio worked, I test it every time I restart the machine, and if it disappears again, I'll let you know.
Thank's for your time.
Tested on: OpenCore 0.5.9

PS: USB type C, not work :(

Thanksssssssss

**Comment by dongcodebmt** [comment]
I can't fix it because I don't have any device type C.
Try removing SSDT-UIAC.aml and patching your usb port with hackintool

**Comment by lehmartins17** [comment]
> I can't fix it because I don't have any device type C.
> Try removing SSDT-UIAC.aml and patching your usb port with hackintool

Perfect! I'm using a UIAC.aml from Hackintool. Have fun!!! Thanks again.

**Comment by dongcodebmt** [comment]
Can you show me screenshot when plugging in type C device in hankintool?

**Comment by lehmartins17** [comment]
> Can you show me screenshot when plugging in type C device in hankintool?

Of course!
[https://i.ibb.co/J3rjWJT/Captura-de-Tela-2020-08-01-a-s-21-14-38.png](url)

My SSDT-UIAC.aml

/*
 * Intel ACPI Component Architecture
 * AML/ASL+ Disassembler version 20180427 (64-bit version)(RM)
 * Copyright (c) 2000 - 2018 Intel Corporation
 * 
 * Disassembling to non-symbolic legacy ASL operators
 *
 * Disassembly of iASL63g05X.aml, Sat Aug  1 21:16:33 2020
 *
 * Original Table Header:
 *     Signature        "SSDT"
 *     Length           0x00000288 (648)
 *     Revision         0x02
 *     Checksum         0x0D
 *     OEM ID           "ACDT"
 *     OEM Table ID     "_UIAC"
 *     OEM Revision     0x00000000 (0)
 *     Compiler ID      "INTL"
 *     Compiler Version 0x20180427 (538444839)
 */
DefinitionBlock ("", "SSDT", 2, "ACDT", "_UIAC", 0x00000000)
{
    Device (UIAC)
    {
        Name (_HID, "UIA00000")  // _HID: Hardware ID
        Name (RMCF, Package (0x02)
        {
            "XHC", 
            Package (0x04)
            {
                "port-count", 
                Buffer (0x04)
                {
                     0x12, 0x00, 0x00, 0x00                         
                }, 

                "ports", 
                Package (0x14)
                {
                    "HS01", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "HS01"
                        }, 

                        "UsbConnector", 
                        0x03, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x01, 0x00, 0x00, 0x00                         
                        }
                    }, 

                    "HS02", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "HS02"
                        }, 

                        "UsbConnector", 
                        0x03, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x02, 0x00, 0x00, 0x00                         
                        }
                    }, 

                    "HS03", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "HS03"
                        }, 

                        "UsbConnector", 
                        0x0A, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x03, 0x00, 0x00, 0x00                         
                        }
                    }, 

                    "HS04", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "HS04"
                        }, 

                        "UsbConnector", 
                        0x0A, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x04, 0x00, 0x00, 0x00                         
                        }
                    }, 

                    "HS05", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "HS05"
                        }, 

                        "UsbConnector", 
                        0x03, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x05, 0x00, 0x00, 0x00                         
                        }
                    }, 

                    "HS07", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "HS07"
                        }, 

                        "UsbConnector", 
                        0x03, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x07, 0x00, 0x00, 0x00                         
                        }
                    }, 

                    "HS09", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "HS09"
                        }, 

                        "UsbConnector", 
                        0x03, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x09, 0x00, 0x00, 0x00                         
                        }
                    }, 

                    "HS10", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "HS10"
                        }, 

                        "UsbConnector", 
                        0x03, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x0A, 0x00, 0x00, 0x00                         
                        }
                    }, 

                    "SS01", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "SS01"
                        }, 

                        "UsbConnector", 
                        0x03, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x11, 0x00, 0x00, 0x00                         
                        }
                    }, 

                    "SS02", 
                    Package (0x06)
                    {
                        "name", 
                        Buffer (0x05)
                        {
                            "SS02"
                        }, 

                        "UsbConnector", 
                        0x03, 
                        "port", 
                        Buffer (0x04)
                        {
                             0x12, 0x00, 0x00, 0x00                         
                        }
                    }
                }
            }
        })
    }
}

**Comment by lehmartins17** [comment]
> Thank you. Please help me check it one last time.
> https://github.com/dongcodebmt/VX5-591G-Hackintosh/raw/master/ACPI/patched/SSDT-UIAC.aml

not work usb type C :(

**Comment by dongcodebmt** [comment]
> > Thank you. Please help me check it one last time.
> > https://github.com/dongcodebmt/VX5-591G-Hackintosh/raw/master/ACPI/patched/SSDT-UIAC.aml
> 
> not work usb type C :(

Maybe I'll use your SSDT-UIAC until I have the equipment to test. However it seems you haven't patched correctly. Only the speed of USB 2.0 (480Mbps)

**Comment by lehmartins17** [comment]
> > > Thank you. Please help me check it one last time.
> > > https://github.com/dongcodebmt/VX5-591G-Hackintosh/raw/master/ACPI/patched/SSDT-UIAC.aml
> > 
> > 
> > not work usb type C :(
> 
> Maybe I'll use your SSDT-UIAC until I have the device to test. However it seems you haven't patched correctly. Only the speed of USB 2.0 (480Mbps)

Exact. I would really like to be able to fix USB type C to 5Gbps. And also the Card Reader, I already tried Sinetek's and voodoo ... None worked.
But any news please let me know? I will do the same here. We will try to leave 100% on the VX5.

**Comment by dongcodebmt** [comment]
The card reader will not work because there is no kext written for it. So you should remove it
For USB try this guide: https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html

**Comment by dongcodebmt** [comment]
Hope you will share it after completion.
